dist: trusty
sudo: false
addons:
  apt:
    packages:
      - libzmq3
language: python
python:
  - "3.4"
before_install:
  - pip install pytest pytest-mock pytest-cov
install:
  - pip install .
  - pip install coveralls
script:
  - py.test --cov=katana --cov-report term-missing tests/
after_success:
  coveralls
