dist: trusty
sudo: false
addons:
  apt:
    packages:
      - libzmq3
language: python
python:
  - "3.4"
before_install:
  - pip install pytest pytest-mock pytest-cov coverage
install:
  - pip install .
  - pip install coveralls
script:
  - python setup.py test
after_success:
  coveralls
